### ISSUE TITLE
Ajuste nos testes unitarios

### ISSUE THREAD

**Issue by JCaye** [academiadev-joinville/desafio-jogo-de-corrida-julio-yan#1]
Nos testes onde se espera que seja levantada uma exceção, o último statement dentro do *try* tem que ser um **Assert.assertFail()**. Sem ele, caso o teste não levante a exceção esperada, ele vai ser considerado aprovado incorretamente.

try {
            needForSpeedApplication.novoPiloto(1l, "Goiaba", LocalDate.of(1992, 10 ,31),
                    LocalDate.of(2017, 03 ,27), BigDecimal.valueOf(15000));
           **Assert.assertFail("Esperava exceção, mas não foi levantada!");**
}catch (Exception e){
            Assert.assertTrue(e instanceof IdentificadorUtilizadoException);
}

**Comment by Yanhenning** [comment]
Corrigido
