### ISSUE TITLE
Inserir comentários nos testes

### ISSUE THREAD

**Issue by JCaye** [academiadev-joinville/desafio-jogo-de-corrida-julio-yan#2]
Inserir uma mensagem de erro nos testes, pra facilitar o debugging caso não dê certo.

try {
            needForSpeedApplication.novoPiloto(1l, "Goiaba", LocalDate.of(1992, 10 ,31),
                    LocalDate.of(2017, 03 ,27), BigDecimal.valueOf(15000));
        }catch (Exception e){
            Assert.assertTrue(**"Exceção inesperada recebida" + e.toString()",** e instanceof IdentificadorUtilizadoException);
        }

**Comment by Yanhenning** [comment]
Comentários adicionados no commit de hoje
